
INSERT INTO public.categoria (id, descricao, nome) VALUES (1, 'Receitas de varios tipos', 'Culinaria');
INSERT INTO public.categoria (id, descricao, nome) VALUES (2, 'Ciencias relacionadas a evolução', 'Ciencias');
INSERT INTO public.categoria (id, descricao, nome) VALUES (3, 'Geometria para crianças', 'Matematica');
INSERT INTO public.categoria (id, descricao, nome) VALUES (4, 'Aprenda a desenvolver softwares', 'Informatica');
INSERT INTO public.categoria (id, descricao, nome) VALUES (5, 'Tudo sobre o espaço', 'Astrologia');

INSERT INTO public.livro (id, nome_autor, texto, titulo, categoria_id) VALUES (1, 'Loiane Groner', 'Sencha Architect is a visual app builder that empowers a developer (and a development team) to design, develop, and deploy apps from a single and integrated environment. It also provides support for Ext JS and Sencha Touch development.Sencha Architect App Development is a practical, hands-on guide that will teach you how to develop a complete application with Ext JS and Sencha Touch. You will learn everything from creating the project, including creating the models, views, controllers and stores, to the build to production. Along the way, this book also highlights the Sencha Architect features that will help you to improve your productivity.', 'Sencha Architect App Development', 4);
INSERT INTO public.livro (id, nome_autor, texto, titulo, categoria_id) VALUES (2, 'Kathy Sierra, Bert Bates', 'Use a cabeça! - Java é uma experiência de aprendizado em programação orientada a objetos (OO) e Java. Projetado de acordo com princípios de aprendizado mentalmente amigáveis, este livro procura mostrar desde aspectos considerados básicos da linguagem a tópicos avançados que incluem segmentos, soquetes de rede e programação distribuída. Alguns conteúdos - A linguagem Java, Desenvolvimento orientado a objetos, Criação, teste e implantação de aplicativos, Uso da biblioteca do API Java, Manipulação de exceções, Uso de vários segmentos, Programação de GUI com o Swing, Rede com RMI e soquetes, Conjuntos e tipos genéricos.', 'Use a Cabeça Java', 4);
INSERT INTO public.livro (id, nome_autor, texto, titulo, categoria_id) VALUES (3, 'Robert Martin', 'Mesmo um código ruim pode funcionar. Mas se ele não for limpo, pode acabar com uma empresa de desenvolvimento. Perdem-se a cada ano horas incontáveis e recursos importantes devido a um código mal escrito. Mas não precisa ser assim. O renomado especialista em software, Robert C. Martin, apresenta um paradigma revolucionário com Código limpo: Habilidades Práticas do Agile Software. Martin se reuniou com seus colegas do Mentor Object para destilar suas melhores e mais ágeis práticas de limpar códigos "dinamicamente" em um livro que introduzirá gradualmente dentro de você os valores da habilidade de um profissional de softwares e lhe tornar um programador melhor –mas só se você praticar.', 'Clean code', 4);
INSERT INTO public.livro (id, nome_autor, texto, titulo, categoria_id) VALUES (4, 'God', 'A astrologia (do grego astron, "astros", "estrelas", "corpos celestes", e logos, "palavra", "estudo") é uma pseudociência[1] segundo a qual as posições relativas dos corpos celestes poderiam prover informação sobre a personalidade, as relações humanas, e outros assuntos relacionados à vida do ser humano. É, como tal, uma atividade divinatória, quando usada como oráculo, mas também pode ser usada como ferramenta de entendimento das personalidades humanas. O suíço Carl Gustav Jung fez estudos a respeito da astrologia; uma de suas teorias baseadas na mesma é a teoria da Sincronicidade. É largamente refutada por uma parte da sociedade por não ter embasamento científico real.', 'Como Surgiu o Estudo das Estrelas', 5);
INSERT INTO public.livro (id, nome_autor, texto, titulo, categoria_id) VALUES (5, 'Maria Braga', 'No âmbito da culinária, receitas são orientações que ajudam as pessoas a, passo a passo, prepararem pratos de comida.[1] As receitas geralmente vêm com seus verbos no modo imperativo, para dar instruções de como preparar o prato. Logo, enquadram-se no grupo dos textos instrucionais. Elas são encontradas em diversas fontes, como livros, sites, programas de televisão, revistas ou até mesmo em jornais, panfletos e aplicações móveis dedicadas à culinária.', 'Oque é Culinaria', 1);
INSERT INTO public.livro (id, nome_autor, texto, titulo, categoria_id) VALUES (6, 'Autor desconhecido', 'Muitos pais acreditam que ensinar matemática para as crianças é função dos professores e só! Não porque não achem importante, mas porque só de falar em matemática muitas pessoas já se arrepiam, achando essa uma das disciplinas mais difíceis da escola. Mas não precisa ser assim, ensinar matemática para as crianças como parte do dia a dia dela, vai ajudá-la a assimilar melhor os conceitos aprendidos na escola. E isso vai se refletir em seu futuro, sem que a disciplina seja encarada de forma negativa. ', 'Matematica Para Crianças', 3);
INSERT INTO public.livro (id, nome_autor, texto, titulo, categoria_id) VALUES (7, 'SKY', 'Ciência (do latim scientia,[1] traduzido por "conhecimento")[2] refere-se a qualquer conhecimento ou prática sistemáticos. Em sentido estrito, ciência refere-se ao sistema de adquirir conhecimento baseado no método científico bem como ao corpo organizado de conhecimento conseguido através de tais pesquisas.[Ref. 1]Este artigo foca o sentido mais estrito da palavra. Embora as duas estejam fortemente interconectadas, a ciência tal como enfatizada neste artigo é muitas vezes referida como ciência experimental a fim de diferenciá-la da ciência aplicada, que é a aplicação da pesquisa científica a necessidades humanas específicas.', 'Discovery Channel', 2);
